import type { Metadata } from "next";

import "./globals.css";
import localFont from "next/font/local";
import BottomNav from "@/components/common/BottomNav/BottomNav";
import MusicPlayer from "@/components/common/MusicPlayer/MusicPlayer";

const myFont = localFont({
  src: "../public/fonts/Poppins/Poppins-Medium.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={myFont.className}
      >
        {children}
        <MusicPlayer />
        <BottomNav />
      </body>
    </html>
  );
}
