import type { Metadata } from "next";
import RootClientLayout from "./RootClientLayout";
import localFont from "next/font/local";
import Provider from '@/redux/Provider';

import "./globals.css";
import Setup from "@/utils/authsetup/Setup";

const myFont = localFont({
  src: "../public/fonts/Poppins/Poppins-Medium.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Provider>
          <Setup />
             <RootClientLayout>{children}</RootClientLayout>
        </Provider>
      </body>
    </html>
  );
}
